name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    
    - name: build (SDL2)
      run: bash ./demo/SDL2/build.sh

    - name: build (GLFW3)
      run: bash ./demo/GLFW3/build.sh
   
