name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libglfw3-dev
    
    - name: build (SDL2)
      working-directory: ./demo/SDL2
      run: bash build.sh

    - name: build (GLFW3)
      working-directory: ./demo/GLFW3
      run: bash build.sh
   
