name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - name: build
      run: |
        cd demo
        bash build.sh
   
